import {useEffect,useState} from 'react';
import api from '../services/api';

const emptyUser={name:'',email:'',password:'',address:'',role:'USER'};
const emptyStore={name:'',email:'',address:'',ownerId:''};
export default function Admin(){
 const[d,setD]=useState({}),[users,setUsers]=useState([]),[stores,setStores]=useState([]),[tab,setTab]=useState('users');
 const[filters,setFilters]=useState({name:'',email:'',address:'',role:''}),[f,setF]=useState(emptyUser),[s,setS]=useState(emptyStore),[sort,setSort]=useState({field:'name',order:'ASC'}),[msg,setMsg]=useState(''),[err,setErr]=useState('');
 async function load(){try{const params={...filters,sort:sort.field,order:sort.order};const[a,b,c]=await Promise.all([api.get('/admin/dashboard'),api.get('/admin/users',{params}),api.get('/admin/stores',{params})]);setD(a.data);setUsers(b.data);setStores(c.data);setErr('')}catch(e){setErr(e.response?.data?.message||'Could not load admin data')}}
 useEffect(()=>{load()},[sort]);
 async function addUser(e){e.preventDefault();setMsg('');setErr('');try{await api.post('/admin/users',f);setF(emptyUser);setMsg('User created');load()}catch(e){setErr(e.response?.data?.message||'Could not create user')}}
 async function addStore(e){e.preventDefault();setMsg('');setErr('');try{await api.post('/admin/stores',s);setS(emptyStore);setMsg('Store created');load()}catch(e){setErr(e.response?.data?.message||'Could not create store')}}
 function toggle(field){setSort(x=>x.field===field?{field,order:x.order==='ASC'?'DESC':'ASC'}:{field,order:'ASC'})}
 const Arrow=({field})=><span className="sort">{sort.field===field?(sort.order==='ASC'?'↑':'↓'):'↕'}</span>;
 return <div><div className="pagehead"><div><p className="eyebrow">ADMIN CONSOLE</p><h1>Dashboard</h1><p>Manage users, stores and platform ratings.</p></div></div>
 {err&&<div className="error">{err}</div>}{msg&&<div className="success">{msg}</div>}
 <div className="stats"><div><b>{d.users||0}</b><span>Total users</span></div><div><b>{d.stores||0}</b><span>Total stores</span></div><div><b>{d.ratings||0}</b><span>Total ratings</span></div></div>
 <div className="grid2"><div className="card"><h2>Add User</h2><form onSubmit={addUser}><input placeholder="Name (20-60)" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/><input placeholder="Email" type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} required/><input placeholder="Password" type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})} required/><input placeholder="Address" value={f.address} onChange={e=>setF({...f,address:e.target.value})} required/><select value={f.role} onChange={e=>setF({...f,role:e.target.value})}><option>USER</option><option>ADMIN</option><option>OWNER</option></select><button className="primary">Create user</button></form></div>
 <div className="card"><h2>Add Store</h2><form onSubmit={addStore}><input placeholder="Store name" value={s.name} onChange={e=>setS({...s,name:e.target.value})} required/><input placeholder="Store email" type="email" value={s.email} onChange={e=>setS({...s,email:e.target.value})} required/><input placeholder="Address" value={s.address} onChange={e=>setS({...s,address:e.target.value})} required/><input placeholder="Owner ID (optional)" value={s.ownerId} onChange={e=>setS({...s,ownerId:e.target.value})}/><button className="primary">Create store</button></form></div></div>
 <div className="filters"><input placeholder="Name" value={filters.name} onChange={e=>setFilters({...filters,name:e.target.value})}/><input placeholder="Email" value={filters.email} onChange={e=>setFilters({...filters,email:e.target.value})}/><input placeholder="Address" value={filters.address} onChange={e=>setFilters({...filters,address:e.target.value})}/><select value={filters.role} onChange={e=>setFilters({...filters,role:e.target.value})}><option value="">All roles</option><option>USER</option><option>ADMIN</option><option>OWNER</option></select><button onClick={load}>Apply filters</button></div>
 <div className="tabs"><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>Users</button><button className={tab==='stores'?'active':''} onClick={()=>setTab('stores')}>Stores</button></div>
 <div className="tablewrap"><table><thead>{tab==='users'?<tr><th onClick={()=>toggle('name')}>Name <Arrow field="name"/></th><th onClick={()=>toggle('email')}>Email <Arrow field="email"/></th><th onClick={()=>toggle('address')}>Address <Arrow field="address"/></th><th onClick={()=>toggle('role')}>Role <Arrow field="role"/></th><th>Rating</th></tr>:<tr><th onClick={()=>toggle('name')}>Name <Arrow field="name"/></th><th onClick={()=>toggle('email')}>Email <Arrow field="email"/></th><th onClick={()=>toggle('address')}>Address <Arrow field="address"/></th><th>Rating</th></tr>}</thead><tbody>{(tab==='users'?users:stores).map(x=><tr key={x.id}><td>{x.name}</td><td>{x.email}</td><td>{x.address}</td>{tab==='users'?<><td><span className="pill">{x.role}</span></td><td>{x.rating==null?'—':`⭐ ${x.rating}`}</td></>:<td>⭐ {x.rating}</td>}</tr>)}</tbody></table></div>
 </div>
}
