const pool=require('../config/db'); const bcrypt=require('bcryptjs');
const validPassword=p=>p.length>=8&&p.length<=16&&/[A-Z]/.test(p)&&/[^A-Za-z0-9]/.test(p); const validName=n=>typeof n==='string'&&n.trim().length>=20&&n.trim().length<=60; const validEmail=e=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(e||'')); const validAddress=a=>typeof a==='string'&&a.trim().length<=400;
async function dashboard(req,res){const [[users]] = await pool.query('SELECT COUNT(*) total FROM users'); const [[stores]]=await pool.query('SELECT COUNT(*) total FROM stores'); const [[ratings]]=await pool.query('SELECT COUNT(*) total FROM ratings'); res.json({users:users.total,stores:stores.total,ratings:ratings.total});}
async function users(req,res){
 const{name='',email='',address='',role=''}=req.query;
 let sql=`SELECT u.id,u.name,u.email,u.address,u.role,u.created_at,CASE WHEN u.role='OWNER' THEN COALESCE(ROUND(AVG(r.rating),2),0) ELSE NULL END rating FROM users u LEFT JOIN stores s ON s.owner_id=u.id LEFT JOIN ratings r ON r.store_id=s.id WHERE u.name LIKE ? AND u.email LIKE ? AND u.address LIKE ?`;
 let p=[`%${name}%`,`%${email}%`,`%${address}%`];
 if(role){sql+=' AND u.role=?';p.push(role)}
 sql+=' GROUP BY u.id ORDER BY '+(['name','email','address','role'].includes(req.query.sort)?'u.'+req.query.sort:'u.name')+' '+(String(req.query.order).toUpperCase()==='DESC'?'DESC':'ASC');
 const[rows]=await pool.query(sql,p);res.json(rows);
}
async function stores(req,res){const{name='',email='',address=''}=req.query;const sort=['name','email','address'].includes(req.query.sort)?req.query.sort:'name';const order=String(req.query.order).toUpperCase()==='DESC'?'DESC':'ASC';const[rows]=await pool.query(`SELECT s.id,s.name,s.email,s.address,COALESCE(ROUND(AVG(r.rating),2),0) rating FROM stores s LEFT JOIN ratings r ON r.store_id=s.id WHERE s.name LIKE ? AND s.email LIKE ? AND s.address LIKE ? GROUP BY s.id ORDER BY ${sort} ${order}`, [`%${name}%`,`%${email}%`,`%${address}%`]);res.json(rows);}
async function createUser(req,res){const{name,email,password,address,role}=req.body;if(!['ADMIN','USER','OWNER'].includes(role))return res.status(400).json({message:'Invalid role'});if(!validName(name))return res.status(400).json({message:'Name must be 20-60 characters'});if(!validEmail(email))return res.status(400).json({message:'Invalid email address'});if(!validAddress(address)||!address.trim())return res.status(400).json({message:'Address is required and must be 400 characters or fewer'});if(!validPassword(password))return res.status(400).json({message:'Password must be 8-16 chars with uppercase and special character'});try{const[r]=await pool.query('INSERT INTO users(name,email,password_hash,address,role) VALUES(?,?,?,?,?)',[name,email,await bcrypt.hash(password,10),address,role]);res.status(201).json({id:r.insertId,message:'User created'});}catch(e){res.status(400).json({message:e.code==='ER_DUP_ENTRY'?'Email already exists':e.message});}}
async function createStore(req,res){const{name,email,address,ownerId}=req.body;if(!name||name.trim().length<1)return res.status(400).json({message:'Store name is required'});if(!validEmail(email))return res.status(400).json({message:'Invalid email address'});if(!validAddress(address)||!address.trim())return res.status(400).json({message:'Address is required and must be 400 characters or fewer'});try{const[r]=await pool.query('INSERT INTO stores(name,email,address,owner_id) VALUES(?,?,?,?)',[name,email,address||'',ownerId||null]);res.status(201).json({id:r.insertId,message:'Store created'});}catch(e){res.status(400).json({message:e.message});}}
module.exports={dashboard,users,stores,createUser,createStore};
